# Generated by Django 2.1.7 on 2019-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('leave_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_of_hours', models.IntegerField()),
            ],
        ),
    ]
