# Generated by Django 2.2 on 2019-04-10 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20190321_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveregistration',
            name='entitlement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.Entitlement'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('user', 'year')},
        ),
    ]
